
package web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerInterfaceImplService", targetNamespace = "http://www.todo.com", wsdlLocation = "http://localhost:6868/01-ws-java-server/ws?wsdl")
public class ServerInterfaceImplService
    extends Service
{

    private final static URL SERVERINTERFACEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERINTERFACEIMPLSERVICE_EXCEPTION;
    private final static QName SERVERINTERFACEIMPLSERVICE_QNAME = new QName("http://www.todo.com", "ServerInterfaceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6868/01-ws-java-server/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERINTERFACEIMPLSERVICE_WSDL_LOCATION = url;
        SERVERINTERFACEIMPLSERVICE_EXCEPTION = e;
    }

    public ServerInterfaceImplService() {
        super(__getWsdlLocation(), SERVERINTERFACEIMPLSERVICE_QNAME);
    }

    public ServerInterfaceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERINTERFACEIMPLSERVICE_QNAME, features);
    }

    public ServerInterfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVERINTERFACEIMPLSERVICE_QNAME);
    }

    public ServerInterfaceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERINTERFACEIMPLSERVICE_QNAME, features);
    }

    public ServerInterfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerInterfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Todo
     */
    @WebEndpoint(name = "todoPort")
    public Todo getTodoPort() {
        return super.getPort(new QName("http://www.todo.com", "todoPort"), Todo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Todo
     */
    @WebEndpoint(name = "todoPort")
    public Todo getTodoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.todo.com", "todoPort"), Todo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERINTERFACEIMPLSERVICE_EXCEPTION!= null) {
            throw SERVERINTERFACEIMPLSERVICE_EXCEPTION;
        }
        return SERVERINTERFACEIMPLSERVICE_WSDL_LOCATION;
    }

}
