
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "todo", targetNamespace = "http://www.todo.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Todo {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://www.todo.com", className = "web.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://www.todo.com", className = "web.RegisterResponse")
    @Action(input = "http://www.todo.com/todo/registerRequest", output = "http://www.todo.com/todo/registerResponse")
    public String register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.todo.com", className = "web.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.todo.com", className = "web.LoginResponse")
    @Action(input = "http://www.todo.com/todo/loginRequest", output = "http://www.todo.com/todo/loginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTodo", targetNamespace = "http://www.todo.com", className = "web.AddTodo")
    @ResponseWrapper(localName = "addTodoResponse", targetNamespace = "http://www.todo.com", className = "web.AddTodoResponse")
    @Action(input = "http://www.todo.com/todo/addTodoRequest", output = "http://www.todo.com/todo/addTodoResponse")
    public String addTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clearTodo", targetNamespace = "http://www.todo.com", className = "web.ClearTodo")
    @ResponseWrapper(localName = "clearTodoResponse", targetNamespace = "http://www.todo.com", className = "web.ClearTodoResponse")
    @Action(input = "http://www.todo.com/todo/clearTodoRequest", output = "http://www.todo.com/todo/clearTodoResponse")
    public String clearTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryTodo", targetNamespace = "http://www.todo.com", className = "web.QueryTodo")
    @ResponseWrapper(localName = "queryTodoResponse", targetNamespace = "http://www.todo.com", className = "web.QueryTodoResponse")
    @Action(input = "http://www.todo.com/todo/queryTodoRequest", output = "http://www.todo.com/todo/queryTodoResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://www.todo.com/todo/queryTodo/Fault/ParseException")
    })
    public String queryTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws ParseException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTodo", targetNamespace = "http://www.todo.com", className = "web.DeleteTodo")
    @ResponseWrapper(localName = "deleteTodoResponse", targetNamespace = "http://www.todo.com", className = "web.DeleteTodoResponse")
    @Action(input = "http://www.todo.com/todo/deleteTodoRequest", output = "http://www.todo.com/todo/deleteTodoResponse")
    public String deleteTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
